### ISSUE TITLE
Test your actual code

### ISSUE THREAD

**Issue by sholladay** [venikman/hapi-server#3]
In `test.js`, you are making a [brand new server](https://github.com/venikman/hapi-server/blob/f4b7f383ccd62b5bf893e857e8ecb6d9e3f00818/test.js#L5) straight from `hapi`. While it technically "works", in the sense that the test runs, the test is kind of pointless because it has nothing to do with your app in [index.js](https://github.com/venikman/hapi-server/blob/master/index.js). The test does not use any of the code from `index.js` in any way. So if your app breaks, the test will not be able to tell you.

You need to make use of your module and test its functionality to make the test worthwhile. Do something with its API and make assertions based on its behavior.

**Comment by venikman** [comment]
can i check how routing works?

**Comment by sholladay** [comment]
Yes. You will want to import the app server and use `server.inject()`: https://hapijs.com/api#serverinjectoptions-callback

**Comment by venikman** [comment]
Should i also use module 'shot'?

**Comment by sholladay** [comment]
No, you do not need `shot` because hapi already uses it. But you do need to  do `server.inject()` on the server from `index.js`, rather than making a separate, unrelated server in the tests..
